framework:
    workflows:
        product:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\BaseProduct
            places:
                - draft
                - published
                - expired
            transitions:
                publish:
                    from: draft
                    to: published
                expire:
                    from: published
                    to: expired
                re_publish:
                    from: expired
                    to: published
                draft_from_expired:
                    from: expired
                    to: draft
                draft_from_published:
                    from: published
                    to: draft
