# config/services.yaml
parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/products'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadDirectory: '%product_images_directory%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
